# Generated by Django 2.1 on 2018-11-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
